version: "3.9"
services:
  api:
    image: quay.io/go-skynet/local-ai:master
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/readyz"]
      interval: 1m
      timeout: 120m
      retries: 120
    ports:
      - 8090:8080
    env_file:
      - .env
    volumes:
      - ./models:/models:cached
      - ./config:/config:cached
    command: ["/usr/bin/local-ai" ]
  localagi:
    build:
      context: .
      dockerfile: Dockerfile
    devices:
    - /dev/snd
    depends_on:
      api:
        condition: service_healthy
    volumes:
      - ./db:/app/db
      - ./data:/data
    env_file:
      - .env